# DockerFile fastApi
FROM python:3.9-slim

#Set working directory
WORKDIR /src

#Copy requirements.txt
COPY requirements.txt requirements.txt

#Install requirements
RUN pip install -r requirements.txt

#Copy project
COPY . .

#Command to run
CMD uvicorn src.main:app --host 0.0.0.0 --port 8000